In [3]:
import numpy as np

ventas_mensuales=np.array([[65,34,21,76],[45,33,31,73],[67,14,22,76],[64,32,21,66],[77,24,54,71],[62,31,23,66],[45,37,71,26],[64,32,45,79],[25,54,71,36],[62,14,26,86],[25,74,31,77],[45,24,71,73]])
print(ventas_mensuales)

total_de_ventas_producto=np.sum(ventas_mensuales, axis=0)
print(total_de_ventas_producto)


StatementMeta(SPK00, 17, 4, Finished, Available)

[[65 34 21 76]
 [45 33 31 73]
 [67 14 22 76]
 [64 32 21 66]
 [77 24 54 71]
 [62 31 23 66]
 [45 37 71 26]
 [64 32 45 79]
 [25 54 71 36]
 [62 14 26 86]
 [25 74 31 77]
 [45 24 71 73]]
[646 403 487 805]
